"""empty message

Revision ID: 144feeb9e1d6
Revises: a0996210eb0d
Create Date: 2025-03-24 15:38:55.199102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144feeb9e1d6'
down_revision = 'a0996210eb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
