"""empty message

Revision ID: 56675e2dda54
Revises: 144feeb9e1d6
Create Date: 2025-03-27 09:05:50.793243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56675e2dda54'
down_revision = '144feeb9e1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
