"""empty message

Revision ID: 87e83c96c13e
Revises: 
Create Date: 2025-03-21 08:08:58.752064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87e83c96c13e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'promotion', ['promotion_id'], ['id'])
        batch_op.drop_column('promotion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('promotion_id')

    # ### end Alembic commands ###
