"""empty message

Revision ID: 9d92679ff5ef
Revises: 56675e2dda54
Create Date: 2025-03-27 15:42:02.677185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d92679ff5ef'
down_revision = '56675e2dda54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumption', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('vip', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vip')
        batch_op.drop_column('consumption')

    # ### end Alembic commands ###
